Add RocketChat notifications on failed build tests (#466)
* Add new github workflow files for api, db, and web; rename old web workflow file

* Use original tag names for images

* Remove numeric tag from workflow name

* Allow github-cicd role to update imagestreamtags

* Add GITHUB_CONTEXT to env of web app workflow for testing

* Troubleshooting of oc actions

* Remove 'needs' for testing

* Modify oc login step due to error

* Fix OCP URL and token secret names

* Test oc with full path

* Running a debug command

* Debug message and run set to .

* Re-add oc test command

* Re-enable oc build and tag commands

* Fix tag command for new Dev image

* Add workflow files for promotion to Test and Prod (currently disabled)

* Enable new workflows for DB and API build/tag for Dev

* Workflow cleanup

* Set placeholder for DB/API verification/pause

* Enable promotion to Test, either on push to master of changes to the api, db, or web directories, or manually

* Disable older Actions so that they are not automatically activated at the same time as promotion to Test

* Update GitHub Action labels for clarity

* Enable promote_to_prod.yml

* Update TEST promotion actions

* Add manual option to Test build action

* Fix name mismatch in workflow

* Update Test promotion for manual workflow trigger

* Debugging of flyway.Dockerfile

* Set version of UBI image used for flyway

* Set up new UBI image for flyway

* Add missing RUN statement in flyway.Dockerfile

* Debugging of flyway.Dockerfile

* Initial cypress test

* cypress testing

* Try working-directory

* Add cypress config file and update cypress workflow

* Testing the inclusion of a Cypress test

* Debug: list cypress video dir

* Reset flyway.Dockerfile

* Remove cypress test workflow

* Save Cypress test videos

* Save cypress videos and screenshots

* Set path for cypress videos

* Add failure message for Cypress tests

* Add RocketChat notification to workflow

* Adjust curl command for RC msg

* Reset alert to send only on failure

* Enabling cypress test of the actual web app

* Add RocketChat notifications to github action (TEST - build from master)

* Set port for npm start

Co-authored-by: Ian Watts <ian@asdf.com>

diff --git a/.github/workflows/dev-web.yml b/.github/workflows/dev-web.yml
--- a/.github/workflows/dev-web.yml
+++ b/.github/workflows/dev-web.yml
@@ -21,26 +21,23 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@master
+
       - uses: actions/setup-node@master
         with:
           node-version: "12"
+
       - name: Install dependencies
         run: npm ci
+
       - name: Unit tests w/ coverage
         run: npm run test -- --coverage --passWithNoTests
+
       - name: LINTing
         run: npm run lint -- --quiet -f codeframe
+
       - name: Prettier
         run: npm run format -- --check
-      # - name: Upload coverage report
-      #   env:
-      #     CC_TEST_REPORTER_ID: ${{ secrets.TestReporterID }}
-      #     CI: "true"
-      #   run: |
-      #     curl -Ls https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
-      #     chmod +x ./cc-test-reporter
-      #     ./cc-test-reporter format-coverage -t lcov -o codeclimate.json
-      #     ./cc-test-reporter upload-coverage -i codeclimate.json
+
   build:
     runs-on: ubuntu-latest
     needs: [test]
@@ -49,9 +46,11 @@ jobs:
         node-version: [10.x, 12.x]
     steps:
       - uses: actions/checkout@v1
+
       - uses: actions/setup-node@v1
         with:
           node-version: ${{ matrix.node-version }}
+
       - name: Cache node modules
         uses: actions/cache@v1
         with:
@@ -61,20 +60,50 @@ jobs:
             ${{ runner.OS }}-build-${{ env.cache-name }}-
             ${{ runner.OS }}-build-
             ${{ runner.OS }}-
+
       - name: npm install and build
         run: |
           npm ci
           npm run build --if-present
         env:
           CI: "true"
-      - name: Cypress test
+
+      - name: Check build result
+        if: ${{ failure() }}
+        run: echo "Error in build step"; exit 1
+
+      - name: npm start
+        run: |
+          PORT=3000 npm start
+
+      - name: Run Cypress tests
         uses: cypress-io/github-action@v2
         with:
           build: npm i -D cypress
           headless: true
           working-directory: ./web
-      - name: List Cypress video directory
-        run: ls -lR .
+
+      - name: Save Cypress video files
+        uses: actions/upload-artifact@v2
+        with:
+          name: cypress-videos
+          path: web/cypress/videos
+
+      - name: Save Cypress screenshots on failure
+        #if: ${{ failure() }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: cypress-screenshots
+          path: web/cypress/screenshots
+
+      - name: Check Cypress test result
+        if: ${{ failure() }}
+        env:
+          ROCKETCHAT_MESSAGE: "There was an error in the Cypress test(s) for the registry app during the ${{ github.workflow }} workflow.  View the output and download test output files at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+        run: |
+          curl -X POST -H 'Content-Type: application/json' --data '{"text":"${{ env.ROCKETCHAT_MESSAGE }}"}' "${{ secrets.ROCKETCHAT_HOOK_URL }}"
+          exit 1
+
   s2i-build:
     runs-on: ubuntu-latest
     needs: [test, build]
